name: articles_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  hive: ^2.0.5
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  test: ^1.19.2
  very_good_analysis: ^2.4.0

