name: local_storage_articles_api
description: A Flutter implementation of the ArticlesApi that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  articles_api:
    path: ../articles_api
  flutter:
    sdk: flutter
  hive: ^2.0.5
  meta: ^1.3.0
  path_provider: ^2.0.8
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0